# Generated by Django 2.2.7 on 2019-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('custom_number', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
