# Generated by Django 2.2.7 on 2019-11-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20191106_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searchapp',
            new_name='Search',
        ),
    ]
